services:
  - type: web
    name: mockdock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1